### ISSUE TITLE
already in use? Key not in response? 

### ISSUE THREAD

**Issue by KUKARAF** [greeschenko/vim9-ollama#2]
# Steps to reproduce 
1. install ollama in WSL `ollama version is 0.1.29`
1a. get vim version: ```VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 01 1980 00:00:00)
Included patches: 1-75
Compiled by nixbld```
3. download required models
4. start vim
5. what do you mean already in use? Why are you trying to start a server if you are meant to communicate with existing server? 
4a. ![image](https://github.com/greeschenko/vim9-ollama/assets/24418303/ed4774b3-3e20-4f26-a3c7-08fb0a555701)
6. ok whatever >> `sudo systemctl start ollama.service`
7. start vim again ![image](https://github.com/greeschenko/vim9-ollama/assets/24418303/9d6efd1a-b774-487a-a857-06d606e07691)

# Question
What is the state of the ollama service and server meant to be?

**Comment by greeschenko** [comment]
Hello, 
error from 4a means that ollama serve already started and all fine in future updates I add check for this 
first `sudo systemctl stop ollama.service`
then try to start `ollama serve` in terminal and show it 
and if no error in ollama server please try `ollama run codellama:latest "write simple web api in javascript"`

**Comment by alexandremcosta** [comment]
> _What about the error on 6?_

Nevermind, I found the reason: I was using `llama3` instead of `codellama`.
The plugin only works with `codellama` model.

**Comment by greeschenko** [comment]
Hello yes for now work only with `codellama` you need pull 2 models
```
ollama pull codellama:latest
ollama pull codellama:7b-code
```

in future I will try to attach another models but for now only codellama work as I expect
